apiVersion: v2 
name: HELM_REPOSITORY_APP-wrapper
description: Wrapper for HELM_REPOSITORY_NAME HELM_REPOSITORY_APP
type: application 
version: 1.0.0 
appVersion: "HELM_APP_VERSION" 
maintainers: 
  - name: Mathod

dependencies:
  - name: HELM_REPOSITORY_APP 
    version: HELM_CHART_VERSION
    repository: HELM_REPOSITORY_URL

sources: 
  - HELM_SOURCES